cluster_name: performance-comparisons

provider:
  type: aws
  region: us-west-2
  cache_stopped_nodes: true
  security_group:
    GroupName: ray-autoscaler-c1

auth:
  ssh_user: ubuntu
  ssh_private_key: ~/.ssh/ci-github-actions-ray-cluster-key.pem

max_workers: 2
available_node_types:
  ray.head.default:
    resources: {"CPU": 0}
    node_config:
      KeyName: ci-github-actions-ray-cluster-key
      InstanceType: m6id.2xlarge
      IamInstanceProfile:
        Name: ray-autoscaler-v1

  ray.worker.default:
    min_workers: 2
    max_workers: 2
    resources: {}
    node_config:
      KeyName: ci-github-actions-ray-cluster-key
      InstanceType: m6id.2xlarge
      IamInstanceProfile:
        Name: ray-autoscaler-v1

setup_commands:
# Mount drive
- sudo mkfs.ext4 /dev/nvme1n1
- sudo mount -t ext4 /dev/nvme1n1 /tmp
- sudo chmod 777 /tmp

# Install dependencies
- sudo apt install unzip
- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
- unzip awscliv2.zip
- sudo ./aws/install
- curl -LsSf https://astral.sh/uv/install.sh | sh
- echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
- source ~/.bashrc
- uv python install 3.9
- uv python pin 3.9
- uv v
- echo "source $HOME/.venv/bin/activate" >> $HOME/.bashrc
- source .venv/bin/activate
- uv pip install pip ray[default] py-spy
# GitHub Actions workflow will replace the `<<SHA>>`, `<<COMMIT>>`, and `<<WHEEL>>` placeholders
# with the actual values as determined dynamically during runtime of the actual workflow.
- uv pip install https://github-actions-artifacts-bucket.s3.amazonaws.com/builds/<<SHA>>/<<COMMIT>>/<<WHEEL>>

# Download benchmarking fixtures
- |
  aws s3 sync \
  s3://eventual-dev-benchmarking-fixtures/uncompressed/tpch-dbgen/2_0/2/parquet/ \
  /tmp/data/2_0/2/parquet/
