name: Install uv, rust, and python
description: Install uv, rust, and python
runs:
  using: composite
  steps:
  - name: Install rust
    shell: bash
    run: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      echo "$HOME/.cargo/bin" >> $GITHUB_PATH

  - name: Install uv
    shell: bash
    run: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source $HOME/.local/bin/env
      echo "$HOME/.local/bin" >> $GITHUB_PATH

  - name: Install python (version 3.9)
    shell: bash
    run: |
      uv python install 3.9
      uv python pin 3.9
