name: Diff commits

on:
  workflow_dispatch:
    inputs:
      commit1:
        description: "First commit hash"
        required: true
      commit2:
        description: "Second commit hash"
        required: true

jobs:
  mount-buildpool:
    runs-on: [self-hosted, linux, x64, bench]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Install `awscli`
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
    - name: Verify `awscli` installation
      run: |
        aws --version

### NEW

# jobs:
#   build-commits:
#     runs-on: [self-hosted, linux, x64, bench]
#     timeout-minutes: 30
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-latest]
#     steps:
#       - name: Set up commit variables
#         run: |
#           echo "COMMIT1=${{ github.event.inputs.commit1 }}" >> $GITHUB_ENV
#           echo "COMMIT2=${{ github.event.inputs.commit2 }}" >> $GITHUB_ENV

#       - name: Attach AWS 'BuildPool' volume
#         run: |

#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

### OLD

# - name: Check Out First Commit
#   shell: bash
#   run: |
#     git checkout $COMMIT1
#     make .venv
#     source .venv/bin/activate
#     make build-release

# - name: Check Out Second Commit
#   shell: bash
#   run: |
#     git checkout $COMMIT2
#     make .venv
#     source .venv/bin/activate
#     make build-release

# - name: Run Test on Custom Runner
#   shell: bash
#   run: |
#     echo "Testing with COMMIT1=$COMMIT1 and COMMIT2=$COMMIT2"
# name: Commit Diff

# on:
#   pull_request:
#   workflow_dispatch:
#     inputs:
#       commit_hash_1:
#         description: "First commit hash"
#         required: true
#       commit_hash_2:
#         description: "Second commit hash"
#         required: true

# jobs:
#   test-hitting-lambda:
#     runs-on: [self-hosted, linux, x64, bench]
#     timeout-minutes: 30
#     strategy:
#       fail-fast: false
#     steps:
#     - name: Test
#       run: |
#         git checkout ${{ github.event.inputs.commit_hash_1 }}
#         ls -lah /dev/disk/by-id
# # jobs:
# #   checkout-and-diff:
# #     runs-on: ubuntu-latest
# #     steps:
# #     - name: Checkout repository
# #       uses: actions/checkout@v4
# #       with:
# #         fetch-depth: 0

# #     - name: Check out first commit
# #       id: commit_hash_1
# #       run: |
# #         git checkout ${{ github.event.inputs.commit_hash_1 }}
# #         make .venv
# #         source .venv/bin/activate
# #         make build
# #     #     mkdir -p ../commit_hash_1
# #     #     mv * ../commit_hash_1
# #     #     mv .[!.]* ../commit_hash_1

# #     # - name: Check out second commit
# #     #   id: commit_hash_2
# #     #   run: |
# #     #     mkdir -p ../commit_hash_2
# #     #     mv * ../commit_hash_2
# #     #     mv .[!.]* ../commit_hash_2

# #       # - name: Run diff between commits
# #       #   run: |
# #       #     ls -las ../commit_hash_1
# #       #     ls -las ../commit_hash_2
