name: Run performance comparisons

on:
  workflow_dispatch:
    inputs:
      c1:
        description: First commit hash
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-commit.yaml
    with:
      commit: ${{ github.event.inputs.c1 }}
      machine_type: buildjet-8vcpu-ubuntu-2204
    secrets:
      aws_role_arn: ${{ secrets.ACTIONS_AWS_ROLE_ARN }}

  run:
    needs: build
    runs-on: [self-hosted, linux, x64, ci-dev]
    strategy:
      fail-fast: true
      matrix:
        commit:
        - ${{ github.event.inputs.c1 }}
    timeout-minutes: 15 # Remove for ssh debugging
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.commit }}
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
    - uses: ./.github/actions/install
    - run: |
        # Dynamically update ray config file
        sed -i 's|<<SHA>>|${{ github.sha }}|g' .github/assets/ray.yaml
        sed -i 's|<<COMMIT>>|${{ matrix.commit }}|g' .github/assets/ray.yaml
        sed -i 's|<<WHEEL>>|${{ needs.build.outputs.wheel }}|g' .github/assets/ray.yaml

        # Download private ssh key
        KEY=$(aws secretsmanager get-secret-value --secret-id ci-github-actions-ray-cluster-key-3 --query SecretString --output text)
        echo "$KEY" >> ~/.ssh/ci-github-actions-ray-cluster-key.pem
        chmod 600 ~/.ssh/ci-github-actions-ray-cluster-key.pem

        # Boot up ray cluster
        uv v
        source .venv/bin/activate
        uv pip install ray[default] boto3
        ray up .github/assets/ray.yaml -y
        HEAD_NODE_IP=$(ray get-head-ip .github/assets/ray.yaml | tail -n 1)
        ssh -o StrictHostKeyChecking=no -fN -L 8265:localhost:8265 -i ~/.ssh/ci-github-actions-ray-cluster-key.pem ubuntu@$HEAD_NODE_IP
        DAFT_RUNNER=ray python -m benchmarking.tpch \
          --skip_questions="2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22" \
          --num_parts 2 \
          --scale_factor 2 \
          --parquet_file_cache /tmp/data \
          --output_csv output.csv \
          --ray_job_dashboard_url http://localhost:8265 \
          --skip_warmup
        ray down .github/assets/ray.yaml -y
